### ISSUE TITLE
problemillas con mechanic design :[

### ISSUE THREAD

**Issue by matbutom** [criticaLateral/practica-mateo-2024#3]
logré crear una prueba, mi objetivo era poder mostrar visualizar una foto con un filtro, usé de referencia el example de poster generator, pero no logro hacer que la imagen se vea. Sólo logré crear el input donde puedo subir la imagen.

este archivo es el código que me ayuda a programar las funciones e inputs

[index.md](https://github.com/user-attachments/files/16566818/index.md)

**Comment by matbutom** [comment]
este otro código es el que usé de referencia para ir guiándome

[index.md](https://github.com/user-attachments/files/16566840/index.md)

**Comment by montoyamoraga** [comment]
hola @matbutom
mira estos archivos que subiste están en index.md,
pero son archivos javascript, la próxima sesión de trabajo conjunto
te muestro una manera más ordenada de conversar por acá, no te preocupes!

**Comment by montoyamoraga** [comment]
@matbutom tomé esos archivos que adjuntaste,
hice nuevas carpetas dentro de my-project/functions,
las nombré mateov0/ y mateov1/
y dentro de cada una hice un archivo index.js
puedes tratar que esos funcionen y entender ese orden,
de cómo crear distintas funciones de diseño con mechanic?
también creo que en este momento es muy útil que comentes
con dudas y certezas lo que vas aprendiendo en los archivos de index.js
te parece?

**Comment by montoyamoraga** [comment]
solucionado la semana pasada en la oficina
