### ISSUE TITLE
uso de p5.riso y efecto halftone

### ISSUE THREAD

**Issue by matbutom** [criticaLateral/practica-mateo-2024#5]
logré agregar la biblioteca al proyecto, insertando el archivo p5.riso.js en la carpeta de functions, lo que me gustaría lograr ahora es poder usar el efecto halftone como input de boolean, estoy un poco bloqueado en resolverlo. Lo demás todo bien, efecto threshold, input slider, etc. 

incluyo además unos errores que me tira chrome que tienen que ser resueltos y el error en mechanic.

<img width="1105" alt="Captura de pantalla 2024-08-19 a la(s) 14 00 28" src="https://github.com/user-attachments/assets/8bb11201-ef2f-43e4-84b2-036d169f61d5">
<img width="418" alt="Captura de pantalla 2024-08-19 a la(s) 14 07 53" src="https://github.com/user-attachments/assets/63a9ab6b-a05a-40c0-bc3a-500f769a3907">

**Comment by montoyamoraga** [comment]
hola @matbutom, estos son mis apuntes entre ahora y cuando nos juntemos a trabajar.
yo me encargo y te aviso si logro arreglar esto :)

1. no me etiquetaste, entonces no me llegó notificación de esta issue, por favor siempre que quieras que lea algo, etiquétame.
2. esta issue no tiene a nadie asignado, entonces no sé si es para que lo hagas tú o yo, por favor siempre asignar a alguien.
3. en tu texto dice que subiste p5riso a functions/, pero no es cierto, está en una carpeta al mismo nivel de functions/, ojo con explicar muy específicamente.
4. habíamos conversado que si usamos p5.riso, hay que citarla, poner créditos, en este momento en ninguna parte textual del repo mencionamos a los autores.
5. no sé si podemos usar p5.riso como archivo, lo que voy a intentar hacer ahora, es aislar la función halfone que quieres, y copiar solo un extracto de la biblioteca, en una función de mechanic.

**Comment by montoyamoraga** [comment]
hola @matbutom,

mira hice lo siguiente:

1. borré las carpetas p5.riso y la función p5.riso, porque es mucho más que lo que necesitamos.
2. me basé en este ejemplo de Processing.py https://tabreturn.github.io/code/processing/python/2019/02/09/processing.py_in_ten_lessons-6.3-_halftones.html para hacer un halftone muy rudimentario
3. cambié los nombres de las inputs a español, dejé un habilitar halfTone y una variable para cambiar el tamaño, es una base para hacer otros efectos.
4. ojo que agregué unos push() y pop() para guardar los estilos, e hice otra variable donde dibujar el halftone.
